var U = {
    moduleName: 'Calendar',
    moduleVersion: '1.2.3',
    utilsVersion: '1.2.0',
    utilsCompileCMD: 'moduleName=Calendar moduleVersion=1.2.3 KEYS=moduleName,moduleVersion,utilsVersion,utilsCompileCMD,__cache,malloc,toDebugStr,logDebug,logWarn,log,error,ErrorBuilder,Schema node compile',
    __cache: {},
    malloc: function(prefix){if(!U.__cache[prefix]){U.__cache[prefix]={};}var obj=U.__cache[prefix];return function(k,v){if(typeof(k)==='object'&&v===undefined){return obj=k;}if(k===undefined&&v===undefined){return obj;}if(typeof(k)!=='string'){throw new Error('invalidParameter');}if(v===undefined){return obj[k];}else{obj[k]=v;}}},
    toDebugStr: function(args){var str='';for(var i=0;i<arguments.length;i++){var arg=arguments[i];if(arg){if(typeof(arg)==='object'||Array.isArray(arg)){if(Array.isArray(arg)){str+='Array('+arg.length+'): \n';}else if(typeof(arg)==='object'){str+='Object: \n';}str+=JSON.stringify(arg,null,'    ');str+='\n';}else{str+=(i>0?' ':'')+arg;}}else{str+=(i>0?' ':'')+arg;}}return str;},
    logDebug: function(){var log=U.toDebugStr.apply(this,arguments);console.log(U.moduleName+': '+log);},
    logWarn: function(){var args=[].slice.call(arguments);args.unshift(U.moduleName+':');console.warn.apply(null,args);},
    log: function(){var args=[].slice.call(arguments);args.unshift(U.moduleName+':');console.log.apply(null,args);},
    error: function(problem,message){var Co=function(problem,message){if(!problem){throw new Error('invalidParameter');}if(problem instanceof Error){this.id=problem.message;}else if(typeof(problem)=='string'){this.id=problem;}else{throw new Error('invalidParameter');}this.message=message||null;};Co.prototype={log:function(){var str=this.id;if(this.message){str+=': '+this.message;}U.logWarn(str);},throw:function(){throw new Error(this.id);},logAndThrow:function(){this.log();this.throw();},toString:function(){return JSON.stringify(this,null,'    ');}};return new Co(problem,message);},
    ErrorBuilder: function(errors){var Co=function(errors){if(errors){if(!Array.isArray(errors)){throw new Error('invalidParameter');}for(var i=0;i<errors.length;i++){if(!errors[i]||!errors[i].id){throw new Error('invalidParameter');}}}this.errors=errors||[];};Co.prototype={push:function(err){if(err instanceof Error){err=new U.error(err.message);}this.errors.push(err);},remove:function(id){var arr=this.errors;var i=-1;for(var j=0;j<arr.length;j++){if(arr[j].id==id){i=j;}}if(i>=0){arr.splice(i,1);}},clear:function(){this.errors=[];},first:function(){return this.errors[0]||null;},last:function(){return this.errors[this.errors.length-1]||null;},toString:function(){return JSON.stringify(this,null,'    ');},hasError:function(id){var arr=this.errors;if(id){for(var i=0;i<arr.length;i++){if(arr[i]&&arr[i].id==id){return true;}}return false;}return arr.length>0;},throwFirst:function(){var len=this.errors.length;if(len==0){throw new Error('emptyErrorBuilder');}this.errors[0].throw();},logFirst:function(){var len=this.errors.length;if(len==0){throw new Error('emptyErrorBuilder');}this.errors[0].log();},logAndThrowFirst:function(){var len=this.errors.length;if(len==0){throw new Error('emptyErrorBuilder');}this.errors[0].logAndThrow();}};return new Co(errors);},
    Schema: function(fn){var Co=function(fn){this.rule={};this.prefix='';this.__control=null;fn.apply(null,[attr.bind(this),attrError.bind(this),attrPrepare.bind(this),attrValidate.bind(this),func.bind(this),funcError.bind(this),setPrefix.bind(this)]);};Co.prototype={prepareAndValidate:function(obj,lan){if(!obj||typeof(obj)!=='object'){throw new Error('invalidParameter');}var eb=new U.ErrorBuilder();for(var k in this.rule){if(this.rule.hasOwnProperty(k)){var v=obj[k];var rule=this.rule[k];var mes=rule.message[lan]||rule.message['default']||('Invalid property "'+k+'".');if(rule.prepare){v=rule.prepare(v,obj);obj[k]=v;}var act=Object.prototype.toString.call(v);var mat=(act===rule.type);if(rule.validate&&!rule.validate(v,mat,obj,act,rule.type)){eb.push(U.error(this.prefix+k,mes));}}}return eb;},normalize:function(obj){var norm={};for(var k in this.rule){if(this.rule.hasOwnProperty(k)){var rule=this.rule[k];var val=obj[k];var typ=Object.prototype.toString.call(val);if(!val||typ!==rule.type){if(rule.type==='[object Array]'){norm[k]=[];}else if(rule.type=='[object Function]'){norm[k]=function(){};}else{norm[k]=null;}}else{norm[k]=val;}}}return norm;}};function attr(name,type){if(!name||typeof(name)!=='string'){throw new Error('invalidParameter');}type=strType(type);if(!type){throw new Error('invalidParameter');}this.__control=name;this.rule[this.__control]={type:type,message:{default:'Invalid attribute "'+name+'".'}};}function func(name){if(!name||typeof(name)!=='string'){throw new Error('invalidParameter');}this.__control=name;this.rule[this.__control]={type:'[object Function]',message:{default:'Invalid function "'+name+'".'}};}var attrError=funcError=function(a,b){if(!a||typeof(a)!=='string'){throw new Error('invalidParameter');}if(b&&typeof(b)!=='string'){throw new Error('invalidParameter');}var lan=(a&&b)?a:'default';var mes=(a&&b)?b:a;if(!this.rule[this.__control]){throw new Error('invalidOrder');}if(!this.rule[this.__control].message){this.rule[this.__control].message={};}this.rule[this.__control].message[lan]=mes;};function attrPrepare(fn){if(!fn||typeof(fn)!=='function'){throw new Error('invalidParameter');}if(!this.rule[this.__control]){throw new Error('invalidOrder');}this.rule[this.__control].prepare=fn;}function attrValidate(fn){if(!fn||typeof(fn)!=='function'){throw new Error('invalidParameter');}if(!this.rule[this.__control]){throw new Error('invalidOrder');}this.rule[this.__control].validate=fn;}function strType(type){if(type===Number){return'[object Number]';}else if(type===String){return'[object String]';}else if(type===Array){return'[object Array]';}else if(type===Date){return'[object Date]';}else if(type===Object){return'[object Object]';}else if(type===Boolean){return'[object Boolean]';}else{null;}}function setPrefix(prefix){this.prefix=prefix;}return new Co(fn);}
};if(typeof(process)==='object'&&typeof(module)==='object'){module.exports=U};